export const SET_SCORE = 'setScore'
export const ADD_POINTS = 'addPoints'
export const SCORE_UPDATED = 'scoreUpdated'
export const PLAY_SOUND = 'playSound'
export const SOUND_CHANGED = 'soundChanged'
export const MUSIC_CHANGED = 'musicChanged'
export const TOGGLE_SOUND = 'toggleSound'
export const TOGGLE_MUSIC = 'toggleMusic'
